name: Validate PR

on:
  pull_request:

# concurrency:
#   group: ${{ github.ref }}
#   cancel-in-progress: true

jobs:
  validate-pr:
#     environment:
#       name: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && 'production' || 'preview' }}

    runs-on: docker

#     permissions:
#       pull-requests: write
#       contents: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: ./.forgejo/actions/install

      - uses: ./.forgejo/actions/validate

      - uses: ./.forgejo/actions/auto-approve-pr
        if: ${{ github.actor == 'renovate' }}
        continue-on-error: true
        with:
          tea-token: ${{ secrets.FORGEJO_TOKEN }}
