name: Validate PR

on:
  pull_request:

# concurrency:
#   group: ${{ github.ref }}
#   cancel-in-progress: true

jobs:
  validate-pr:

    runs-on: docker

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: https://github.com/oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2
        with:
          bun-version-file: ".bun-version"

      - shell: bash
        run: bun install

      - uses: ./.forgejo/actions/validate

      - uses: ./.forgejo/actions/auto-approve-pr
        if: ${{ github.actor == 'renovate' }}
        continue-on-error: true
        with:
          tea-token: ${{ secrets.FORGEJO_TOKEN }}
