name: "validate"
description: "validate and check codebase"

runs:
  using: "composite"

  steps:
    - name: Biome
      shell: bash
      run: node --run biome:ci

    - name: Test
      shell: bash
      run: node --run test

    - name: Typecheck
      shell: bash
      run: node --run typecheck
