name: "validate"
description: "validate and check codebase"

runs:
  using: "composite"

  steps:
    - name: Biome
      shell: bash
      run: pnpm biome:ci

    - name: Test
      shell: bash
      run: pnpm test

    - name: Typecheck
      shell: bash
      run: pnpm typecheck
